import { resolve } from 'node:path'
import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import { pagesPlugin } from './scripts/pages.ts'

// Multi-page app: the landing page, the editor and the visualizer are separate
// entries sharing one React stack; /en/… copies are generated by pagesPlugin.
export default defineConfig({
  base: '/',
  plugins: [react(), pagesPlugin()],
  build: {
    target: 'es2022',
    rollupOptions: {
      input: {
        home: resolve(import.meta.dirname, 'index.html'),
        editor: resolve(import.meta.dirname, 'editor/index.html'),
        viewer: resolve(import.meta.dirname, 'viewer/index.html'),
      },
    },
  },
  test: { include: ['src/**/*.test.ts'] },
})
